### ISSUE TITLE
Exception on repo init 

### ISSUE THREAD

**Issue by sebastianbenz** [esrlabs/git-repo#15]
Exception on repo init (OSX, Python 3.3.5)

```
repo init -u https://.../manifest.git -m default.xml -g all,-notdefault,-notci,snapshot
Error in sitecustomize; set PYTHONVERBOSE for traceback:
ValueError: list.remove(x): x not in list
Traceback (most recent call last):
  File "/Users/sebastian/bin/repo", line 709, in <module>
    main(sys.argv[1:])
  File "/Users/sebastian/bin/repo", line 675, in main
    _Init(args)
  File "/Users/sebastian/bin/repo", line 207, in _Init
    _Clone(url, dst, opt.quiet)
  File "/Users/sebastian/bin/repo", line 459, in _Clone
    if _DownloadBundle(url, local, quiet):
  File "/Users/sebastian/bin/repo", line 381, in _DownloadBundle
    m = re.compile(r'^url\.(.*)\.insteadof (.*)$').match(line)
TypeError: can't use a string pattern on a bytes-like object
```

**Comment by AkshayRaj** [comment]
Hey, I am also getting the same issue on repo init. Is this resolved?

**Comment by thomaspons** [comment]
Same error here with Python 3.4.3 and windows 7

**Comment by mputz86** [comment]
Should be gone on the stable branch with the resync to google git-repo and the Python2.7+ support. Thank you very much!
