### ISSUE TITLE
ValueError on repo init

### ISSUE THREAD

**Issue by nhtehsu** [esrlabs/git-repo#19]
I get the following error when I try to run repo on windows 7

D:\172.16.10.72.gerrit.repo\test>repo init -u ssh://172.16.10.72:29418/manifest/test                                                
...
Get ssh://172.16.10.72:29418/manifest/test                                                                                          
Traceback (most recent call last):                                                                                                  
  File "C:\Users\Administrator.e430-PC\git-repo-win\main.py", line 532, in <module>                                                 
    result = _Main(sys.argv[1:])                                                                                                    
  File "C:\Users\Administrator.e430-PC\git-repo-win\main.py", line 505, in _Main                                                    
    result = repo._Run() or 0                                                                                                       
  File "C:\Users\Administrator.e430-PC\git-repo-win\main.py", line 158, in _Run                                                     
    result = cmd.Execute(copts, cargs)                                                                                              
  File "C:\Users\Administrator.e430-PC\git-repo-win\subcmds\init.py", line 353, in Execute                                          
    self._SyncManifest(opt)                                                                                                         
  File "C:\Users\Administrator.e430-PC\git-repo-win\subcmds\init.py", line 139, in _SyncManifest                                    
    m._InitGitDir()                                                                                                                 
  File "C:\Users\Administrator.e430-PC\git-repo-win\project.py", line 1893, in _InitGitDir                                          
    self._InitHooks()                                                                                                               
  File "C:\Users\Administrator.e430-PC\git-repo-win\project.py", line 1926, in _InitHooks                                           
    portable.os_link(stock_hook, dst)                                                                                               
  File "C:\Users\Administrator.e430-PC\git-repo-win\portable.py", line 55, in os_link                                               
    src = os.path.relpath(src, os.path.dirname(dst))                                                                                
  File "C:\Python33\lib\ntpath.py", line 622, in relpath                                                                            
    raise ValueError(error)                                                                                                         
ValueError: path is on mount 'C:', start on mount 'D:'

**Comment by mputz86** [comment]
Relative links on Windows are restricted to a single volume according to https://msdn.microsoft.com/en-us/library/windows/desktop/aa363878(v=vs.85).aspx .

I make this a new feature requests for the stable branch to create only relative links on windows when necessary.
Thank you very much!
