### ISSUE TITLE
Temp File Isnt Created When Pushing Multiple Repo's

### ISSUE THREAD

**Issue by VeryCrushed** [esrlabs/git-repo#36]
Traceback (most recent call last):
  File "C:\Users\Andrew\Documents\Ryuusoft\git-repo\main.py", line 538, in <module>
    _Main(sys.argv[1:])
  File "C:\Users\Andrew\Documents\Ryuusoft\git-repo\main.py", line 512, in _Main
    result = repo._Run(argv) or 0
  File "C:\Users\Andrew\Documents\Ryuusoft\git-repo\main.py", line 185, in _Run
    result = cmd.Execute(copts, cargs)
  File "C:\Users\Andrew\Documents\Ryuusoft\git-repo\subcmds\push.py", line 388, in Execute
    self._MultipleBranches(opt, pending)
  File "C:\Users\Andrew\Documents\Ryuusoft\git-repo\subcmds\push.py", line 182, in _MultipleBranches
    script = Editor.EditString("\n".join(script)).split("\n")
  File "C:\Users\Andrew\Documents\Ryuusoft\git-repo\editor.py", line 99, in EditString
    % (str(e), editor, path))
error.EditorError: editor failed, [Error 2] The system cannot find the file specified: vi c:\users\andrew\appdata\local\temp\tmpd3bd97

**Comment by VeryCrushed** [comment]
Nevermind, found out why vi is the default editor which does not appear to be included in git by default. Solution was to set the git editor using git config --global core.editor "vim"

Maybe add this to the readme?

**Comment by mputz86** [comment]
Thank you anyway ! - it is already in the documentation (set GIT_EDITOR env var) - you are not the first one who have seen this misleading error message :).
