### ISSUE TITLE
rmtree python failed when switching from a branch1 to Branch2

### ISSUE THREAD

**Issue by microwan** [esrlabs/git-repo#37]
Hello ,

I am on the last stable branch of git-repo
I have python27
and i used GIT BASH 2.8.1

I have an issue on Windows
1) repo init -b branch1
    "Manifest contains a module **DocGeneration**"
2) repo sync
    OK   
3) repo init -b branch2
"Manifest does not contain a module **DocGeneration**"
4) repo sync

Deleting obsolete path C:/Project/SPC5_DEV/DEV/Tools/DocGeneration
Traceback (most recent call last):
  File "C:\project\git-repo\main.py", line 538, in <module>
    _Main(sys.argv[1:])
  File "C:\project\git-repo\main.py", line 512, in _Main
    result = repo._Run(argv) or 0
  File "C:\project\git-repo\main.py", line 185, in _Run
    result = cmd.Execute(copts, cargs)
  File "C:\project\git-repo\subcmds\sync.py", line 753, in Execute
    if self.UpdateProjectList():
  File "C:\project\git-repo\subcmds\sync.py", line 493, in UpdateProjectList
    shutil.rmtree(project.worktree)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Python27\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 5] Access is denied: 'C:/Project/SPC5_DEV/DEV/Tools/DocGeneration\\.git\\objects\\pack\\pack-770eb7371be8e228d1bd76eda4a516c99289ba50.idx'

rmtree is KO

            Best regards

                               Erwan

**Comment by mputz86** [comment]
Thanks for the pull request regarding this issue :) - sorry for the delay until it got merged into the stable branch.
