### ISSUE TITLE
WindowsError: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by pold500** [esrlabs/git-repo#67]
Traceback (most recent call last):
  File "c:\dev\here\sop4\.repo\repo/main.py", line 538, in <module>
    _Main(sys.argv[1:])
  File "c:\dev\here\sop4\.repo\repo/main.py", line 512, in _Main
    result = repo._Run(argv) or 0
  File "c:\dev\here\sop4\.repo\repo/main.py", line 181, in _Run
    portable.NoPager(cmd)
  File "c:\dev\here\sop4\.repo\repo\portable.py", line 277, in NoPager
    RunWindowsShell(cmd)
  File "c:\dev\here\sop4\.repo\repo\portable.py", line 281, in RunWindowsShell
    redirect_all(executable)
  File "c:\dev\here\sop4\.repo\repo\portable.py", line 288, in redirect_all
    p = subprocess.Popen([executable], stdin=subprocess.PIPE, stdout=old_sysout, stderr=old_syserr)
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by jsotogaviard** [comment]
+1

**Comment by shanmukhananda** [comment]
+1

**Comment by grv87** [comment]
Dupe of #53?

**Comment by pBogey** [comment]
Wow this is old. I have the same issue. Seems it's trying to execute `cat` command.

EDIT: added cygwin to PATH and I the error changed :D. Anyway, that's the issue.
