### ISSUE TITLE
windsow 10 : WindowsError: [Error 2]

### ISSUE THREAD

**Issue by rouzi** [esrlabs/git-repo#69]
Traceback (most recent call last):
  File "E:\logger\.repo\repo/main.py", line 538, in <module>
    _Main(sys.argv[1:])
  File "E:\logger\.repo\repo/main.py", line 512, in _Main
    result = repo._Run(argv) or 0
  File "E:\logger\.repo\repo/main.py", line 181, in _Run
    portable.NoPager(cmd)
  File "E:\logger\.repo\repo\portable.py", line 277, in NoPager
    RunWindowsShell(cmd)
  File "E:\logger\.repo\repo\portable.py", line 281, in RunWindowsShell
    redirect_all(executable)
  File "E:\logger\.repo\repo\portable.py", line 288, in redirect_all
    p = subprocess.Popen([executable], stdin=subprocess.PIPE, stdout=old_sysout, stderr=old_syserr)
  File "D:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "D:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2]

**Comment by jsotogaviard** [comment]
+1

**Comment by cagdascirit** [comment]
+1

**Comment by grv87** [comment]
Duplicate of #53?

**Comment by AttITuder** [comment]
+1
