### ISSUE TITLE
Windows Error on repo init 

### ISSUE THREAD

**Issue by AttITuder** [esrlabs/git-repo#74]
* [new tag]         v0.4.9               -> v0.4.9
Traceback (most recent call last):
  File "C:\Users\dpc\Desktop\winRepo\.repo\repo/main.py", line 538, in <module>
    _Main(sys.argv[1:])
  File "C:\Users\dpc\Desktop\winRepo\.repo\repo/main.py", line 512, in _Main
    result = repo._Run(argv) or 0
  File "C:\Users\dpc\Desktop\winRepo\.repo\repo/main.py", line 181, in _Run
    portable.NoPager(cmd)
  File "C:\Users\dpc\Desktop\winRepo\.repo\repo\portable.py", line 277, in NoPag
er
    RunWindowsShell(cmd)
  File "C:\Users\dpc\Desktop\winRepo\.repo\repo\portable.py", line 281, in RunWi
ndowsShell
    redirect_all(executable)
  File "C:\Users\dpc\Desktop\winRepo\.repo\repo\portable.py", line 288, in redir
ect_all
    p = subprocess.Popen([executable], stdin=subprocess.PIPE, stdout=old_sysout,
 stderr=old_syserr)
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2]

**Comment by grv87** [comment]
@AttITuder, have you seen discussion at #53, that you need to have `cat` and `less` available in `PATH`?

**Comment by AttITuder** [comment]
I have set the environment variables to follow the steps

**Comment by AttITuder** [comment]
> @AttITuder, have you seen discussion at #53, that you need to have `cat` and `less` available in `PATH`?

I have set the environment variables to follow the steps
