### ISSUE TITLE
windows10 WindowsError: [Error 1] %s: %s

### ISSUE THREAD

**Issue by dangervon** [esrlabs/git-repo#78]
$ repo init -u https://android.googlesource.com/platform/manifest
Get https://android.googlesource.com/platform/manifest
Traceback (most recent call last):
  File "D:\source\android\.repo\repo/main.py", line 547, in <module>
    _Main(sys.argv[1:])
  File "D:\source\android\.repo\repo/main.py", line 522, in _Main
    result = repo._Run(argv) or 0
  File "D:\source\android\.repo\repo/main.py", line 184, in _Run
    result = cmd.Execute(copts, cargs)
  File "D:\source\android\.repo\repo\subcmds\init.py", line 424, in Execute
    self._SyncManifest(opt)
  File "D:\source\android\.repo\repo\subcmds\init.py", line 188, in _SyncManifest
    m._InitGitDir(mirror_git=mirrored_manifest_git)
  File "D:\source\android\.repo\repo\project.py", line 2389, in _InitGitDir
    self._UpdateHooks()
  File "D:\source\android\.repo\repo\project.py", line 2409, in _UpdateHooks
    self._InitHooks()
  File "D:\source\android\.repo\repo\project.py", line 2439, in _InitHooks
    os.path.relpath(stock_hook, os.path.dirname(dst)), dst)
  File "D:\source\android\.repo\repo\platform_utils.py", line 193, in symlink
    platform_utils_win32.create_filesymlink(_makelongpath(source), link_name)
  File "D:\source\android\.repo\repo\platform_utils_win32.py", line 138, in create_filesymlink
    _create_symlink(source, link_name, SYMBOLIC_LINK_FLAG_FILE)
  File "D:\source\android\.repo\repo\platform_utils_win32.py", line 166, in _create_symlink
    'Error creating symbolic link \"%s\"'.format(link_name))
  File "D:\source\android\.repo\repo\platform_utils_win32.py", line 225, in _raise_winerror
    raise WinError(code, error_desc)
WindowsError: [Error 1] %s: %s

**Comment by grv87** [comment]
Looks like [the problem with symlinks, described in README](https://github.com/esrlabs/git-repo#fix-priviledges-to-allow-for-creation-of-symbolic-links)
