### ISSUE TITLE
get "FileExistsError: [WinError 183]" when repo sync

### ISSUE THREAD

**Issue by Awille** [esrlabs/git-repo#85]
I use "https://mirrors.tuna.tsinghua.edu.cn/help/AOSP/" to download aosp, firsr i download the latest code in tar:
```
curl -OC - https://mirrors.tuna.tsinghua.edu.cn/aosp-monthly/aosp-latest.tar # download latest code tar
tar xf aosp-latest.tar
cd AOSP   
# it just has a .repo file when unzip.
repo sync 
```
I met this error when repo sync:
```
PS E:\AOSP\aosp\aosp> repo sync
Traceback (most recent call last):
  File "E:\AOSP\aosp\aosp\.repo\repo/main.py", line 705, in <module>
    _Main(sys.argv[1:])
  File "E:\AOSP\aosp\aosp\.repo\repo/main.py", line 681, in _Main
    result = repo._Run(name, gopts, argv) or 0
  File "E:\AOSP\aosp\aosp\.repo\repo/main.py", line 228, in _Run
    result = run()
  File "E:\AOSP\aosp\aosp\.repo\repo/main.py", line 219, in <lambda>
    run = lambda: self._RunLong(name, gopts, argv) or 0
  File "E:\AOSP\aosp\aosp\.repo\repo/main.py", line 314, in _RunLong
    result = cmd.Execute(copts, cargs)
  File "E:\AOSP\aosp\aosp\.repo\repo\subcmds\sync.py", line 1278, in Execute
    self._UpdateAllManifestProjects(opt, mp, manifest_name)
  File "E:\AOSP\aosp\aosp\.repo\repo\subcmds\sync.py", line 1118, in _UpdateAllManifestProjects
    self._UpdateManifestProject(opt, mp, manifest_name)
  File "E:\AOSP\aosp\aosp\.repo\repo\subcmds\sync.py", line 1158, in _UpdateManifestProject
    mp.Sync_LocalHalf(syncbuf, submodules=mp.manifest.HasSubmodules)
  File "E:\AOSP\aosp\aosp\.repo\repo\project.py", line 1329, in Sync_LocalHalf
    self._InitWorkTree(force_sync=force_sync, submodules=submodules)
  File "E:\AOSP\aosp\aosp\.repo\repo\project.py", line 2872, in _InitWorkTree
    platform_utils.symlink(os.path.relpath(self.gitdir, self.worktree), dotgit)
  File "E:\AOSP\aosp\aosp\.repo\repo\platform_utils.py", line 42, in symlink
    platform_utils_win32.create_dirsymlink(_makelongpath(source), link_name)
  File "E:\AOSP\aosp\aosp\.repo\repo\platform_utils_win32.py", line 141, in create_dirsymlink
    _create_symlink(source, link_name, SYMBOLIC_LINK_FLAG_DIRECTORY)
  File "E:\AOSP\aosp\aosp\.repo\repo\platform_utils_win32.py", line 157, in _create_symlink
    'Error creating symbolic link \"%s\"'.format(link_name))
  File "E:\AOSP\aosp\aosp\.repo\repo\platform_utils_win32.py", line 209, in _raise_winerror
    raise WinError(code, error_desc)
FileExistsError: [WinError 183] %s: %s 

```
how can i fix it?

**Comment by chc7042** [comment]
delete current vertion of git and.. re install git using latest version.
also take care about Symbolic link option when setup wizard almost last selection page.
after install git. execute git bash under administrator's previlege.
