### ISSUE TITLE
exception when user.email and user.name not configured when repo init

### ISSUE THREAD

**Issue by andreibechet** [esrlabs/git-repo#9]
```
Traceback (most recent call last):
  File "/home/andreibechet/Projects/audicgw/.repo/repo/main.py", line 532, in <module>
    result = _Main(sys.argv[1:])
  File "/home/andreibechet/Projects/audicgw/.repo/repo/main.py", line 505, in _Main
    result = repo._Run() or 0
  File "/home/andreibechet/Projects/audicgw/.repo/repo/main.py", line 158, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/andreibechet/Projects/audicgw/.repo/repo/subcmds/init.py", line 358, in Execute
    self._ConfigureUser()
  File "/home/andreibechet/Projects/audicgw/.repo/repo/subcmds/init.py", line 256, in _ConfigureUser
    name = self._Prompt('Your Name', mp.UserName)
  File "/home/andreibechet/Projects/audicgw/.repo/repo/project.py", line 623, in UserName
    self._LoadUserIdentity()
  File "/home/andreibechet/Projects/audicgw/.repo/repo/project.py", line 636, in _LoadUserIdentity
    u = self.bare_git.var('GIT_COMMITTER_IDENT')
  File "/home/andreibechet/Projects/audicgw/.repo/repo/project.py", line 2220, in runner
    p.stderr))
error.GitError: manifests var: b'\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email "you@example.com"\n  git config --global user.name "Your Name"\n\nto set your account\'s default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: unable to auto-detect email address (got \'andreibechet@andreibechet-ThinkPad-T440p.(none)\')\n'
```

**Comment by mputz86** [comment]
Valid error of git repo, at least the last line will look much more pretty on the stable branch ;). Thanks!
